### ISSUE TITLE
How do i change the color of the indicator?

### ISSUE THREAD

**Issue by Pagi-Maula** [JM-Enthusiast/latte-indicator-win11#3]
I want to change the blue colour of the indicator to something that fits my colour scheme more. How do i do it?

**Comment by JM-Enthusiast** [comment]
It is not possible to change the color of the indicator line currently unfortunately. It is based on your theme's accent color.

But it's a great idea! 

Sadly I don't have too much time to work on this right now, so I can't give you an ETA.
I'll let you know when it's implemented. Sorry for the inconvenience and thanks for the suggestion!

**Comment by JM-Enthusiast** [comment]
Hey! Sorry for the quite long delay, I was very busy. But it should now be possible to define your own color to be used for the line indicator!

The KDE Store is currently down (for me at least) so I cannot upload the package right now but if you want to test out the changes you can clone the repo and manually update it from there.

Please let me know if it works properly and if it does what you wanted so I can close the issue.

**Comment by JM-Enthusiast** [comment]
I managed to upload the package if you prefer updating it that way - https://www.pling.com/p/1621535

**Comment by Pagi-Maula** [comment]
Oh yeah it is working just perfectly! Thank you very much for bringing this update! It is so cool! Now my rices will look even more cool! I want to thank you yet again...
